import { Trip, User } from './types'

export const currentUser: User = {
  id: '1',
  name: 'Alex Rivera',
  email: 'alex@traveloop.com',
  avatar: 'AR',
}

export const mockTrips: Trip[] = [
  {
    id: '1',
    name: 'Southeast Asia Adventure',
    description: 'Exploring temples, street food, and tropical beaches across three countries.',
    coverImage: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80',
    startDate: '2026-06-15',
    endDate: '2026-07-05',
    status: 'upcoming',
    isPublic: true,
    totalBudget: 3200,
    stops: [
      {
        id: 's1',
        city: 'Bangkok',
        country: 'Thailand',
        startDate: '2026-06-15',
        endDate: '2026-06-20',
        days: 5,
        accommodation: 280,
        transport: 120,
        activities: [
          { id: 'a1', name: 'Grand Palace', type: 'culture', duration: 3, cost: 15, description: 'Historic palace complex and Wat Phra Kaew', time: '09:00' },
          { id: 'a2', name: 'Chatuchak Market', type: 'shopping', duration: 4, cost: 0, description: 'Massive weekend market with 15,000 stalls', time: '10:00' },
          { id: 'a3', name: 'Floating Market Tour', type: 'sightseeing', duration: 5, cost: 45, description: 'Damnoen Saduak boat tour', time: '07:00' },
          { id: 'a4', name: 'Thai Cooking Class', type: 'food', duration: 4, cost: 55, description: 'Learn to cook 4 traditional dishes', time: '14:00' },
        ],
      },
      {
        id: 's2',
        city: 'Chiang Mai',
        country: 'Thailand',
        startDate: '2026-06-20',
        endDate: '2026-06-25',
        days: 5,
        accommodation: 220,
        transport: 80,
        activities: [
          { id: 'a5', name: 'Doi Inthanon Trek', type: 'adventure', duration: 8, cost: 60, description: 'Trek to Thailand\'s highest peak', time: '06:00' },
          { id: 'a6', name: 'Elephant Sanctuary', type: 'adventure', duration: 6, cost: 80, description: 'Ethical elephant experience', time: '08:00' },
          { id: 'a7', name: 'Night Bazaar', type: 'shopping', duration: 3, cost: 0, description: 'Evening market with handicrafts', time: '19:00' },
        ],
      },
      {
        id: 's3',
        city: 'Bali',
        country: 'Indonesia',
        startDate: '2026-06-25',
        endDate: '2026-07-05',
        days: 10,
        accommodation: 650,
        transport: 150,
        activities: [
          { id: 'a8', name: 'Ubud Rice Terraces', type: 'sightseeing', duration: 4, cost: 10, description: 'Tegallalang UNESCO terraces', time: '08:00' },
          { id: 'a9', name: 'Surf Lesson Kuta', type: 'adventure', duration: 3, cost: 35, description: 'Beginner surf at Kuta Beach', time: '10:00' },
          { id: 'a10', name: 'Temple Hopping', type: 'culture', duration: 6, cost: 20, description: 'Tanah Lot, Uluwatu, Besakih', time: '09:00' },
          { id: 'a11', name: 'Spa Day', type: 'sightseeing', duration: 4, cost: 45, description: 'Traditional Balinese massage', time: '14:00' },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'European Rail Journey',
    description: 'City hopping through Western Europe by train, from Paris to Prague.',
    coverImage: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80',
    startDate: '2026-09-01',
    endDate: '2026-09-18',
    status: 'planning',
    isPublic: false,
    totalBudget: 4800,
    stops: [
      {
        id: 's4',
        city: 'Paris',
        country: 'France',
        startDate: '2026-09-01',
        endDate: '2026-09-05',
        days: 4,
        accommodation: 520,
        transport: 90,
        activities: [
          { id: 'a12', name: 'Eiffel Tower', type: 'sightseeing', duration: 2, cost: 30, description: 'Summit visit at dusk', time: '18:00' },
          { id: 'a13', name: 'Louvre Museum', type: 'culture', duration: 5, cost: 17, description: 'World\'s largest art museum', time: '10:00' },
          { id: 'a14', name: 'Seine River Cruise', type: 'sightseeing', duration: 2, cost: 25, description: 'Bateaux Mouches evening cruise', time: '20:00' },
        ],
      },
      {
        id: 's5',
        city: 'Amsterdam',
        country: 'Netherlands',
        startDate: '2026-09-05',
        endDate: '2026-09-09',
        days: 4,
        accommodation: 480,
        transport: 60,
        activities: [
          { id: 'a15', name: 'Rijksmuseum', type: 'culture', duration: 4, cost: 22, description: 'Dutch Golden Age masterpieces', time: '10:00' },
          { id: 'a16', name: 'Canal Bike Tour', type: 'adventure', duration: 3, cost: 18, description: 'Pedal boat through the canals', time: '14:00' },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Japan Cherry Blossom',
    description: 'Sakura season across Tokyo, Kyoto, and Osaka.',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
    startDate: '2025-03-25',
    endDate: '2025-04-10',
    status: 'completed',
    isPublic: true,
    totalBudget: 5200,
    stops: [
      {
        id: 's6',
        city: 'Tokyo',
        country: 'Japan',
        startDate: '2025-03-25',
        endDate: '2025-04-01',
        days: 7,
        accommodation: 840,
        transport: 200,
        activities: [
          { id: 'a17', name: 'Shinjuku Gyoen', type: 'sightseeing', duration: 3, cost: 5, description: 'Best sakura viewing in Tokyo', time: '09:00' },
          { id: 'a18', name: 'Tsukiji Outer Market', type: 'food', duration: 2, cost: 30, description: 'Fresh sushi breakfast', time: '08:00' },
          { id: 'a19', name: 'Senso-ji Temple', type: 'culture', duration: 2, cost: 0, description: 'Tokyo\'s oldest temple', time: '07:00' },
        ],
      },
    ],
  },
]

export const popularDestinations = [
  { city: 'Tokyo', country: 'Japan', image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80', costIndex: '$$$$', rating: 4.9 },
  { city: 'Bali', country: 'Indonesia', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&q=80', costIndex: '$$', rating: 4.8 },
  { city: 'Paris', country: 'France', image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&q=80', costIndex: '$$$', rating: 4.7 },
  { city: 'Lisbon', country: 'Portugal', image: 'https://images.unsplash.com/photo-1548707309-dcebeab9ea9b?w=400&q=80', costIndex: '$$', rating: 4.8 },
  { city: 'Kyoto', country: 'Japan', image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400&q=80', costIndex: '$$$', rating: 4.9 },
  { city: 'Barcelona', country: 'Spain', image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=400&q=80', costIndex: '$$$', rating: 4.7 },
]
